recipe: default.v1

assistant_id: 20240325-133028-wooden-bosun

language: "id"

pipeline:
- name: WhitespaceTokenizer
  "intent_tokenization_flag": False
  "intent_split_symbol": "_"
  "token_pattern": None
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: True
- name: ResponseSelector
  epochs: 100
  constrain_similarities: True
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
- name: "RulePolicy"
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
  restrict_rules: true
  check_for_contradictions: true

